spring.application.name=TBAppCollections-1
# show sql 
spring.jpa.show-sql=true

# readable format 
spring.jpa.properties.hibernate.format_sql=true

# Enable H2 console
#spring.h2.console.enabled=true
#spring.datasource.url=jdbc:h2:mem:ticket

# for mysql database 
spring.datasource.url=jdbc:mysql://localhost:3306/springboot
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update